name: glucolook
description: "Saliva-based instant glucose monitoring."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  palette_generator: ^0.3.3+3
  image_picker: ^1.0.7
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  camera: ^0.10.5+9
  image: ^3.0.1
  path_provider: ^2.0.2
  shared_preferences: ^2.0.7
  firebase_database: ^10.5.4
  firebase_core: ^2.30.1
  fl_chart: ^0.68.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
